# Version file generated by setup.py 

short_version = '0.1.0' 
version = '0.1.0' 
full_version = '0.1.0.dev0+ad6adab' 
git_revision = 'ad6adab71c8783e218671a6e4bcc36dc8e5eb59d' 
release = False 


if not release: 
    version = full_version 
