# Version file generated by setup.py 

short_version = '0.1.0' 
version = '0.1.0' 
full_version = '0.1.0.dev0+3fe32ee' 
git_revision = '3fe32eed7a4ae3d19f9a40541fe2824a93112027' 
release = False 


if not release: 
    version = full_version 
